### PR TITLE
Deduplicate and remove mentions from excluded spans for TAC14

### PR DESCRIPTION
**Pull request by jnothman**
This mostly modifies prepare-tac and the scripts that call it.

I've not got tests covering these cases, which is probably bad, but I may merge soon in any case.

### CODE REVIEW

**Comment by jnothman** [comment]
@benhachey, you may want to check that you find the changes to scripts/run_* produce a condonable interface.

**Comment by benhachey** [comment]
Thanks for the ping. Interface change is fine by me. Please update the wiki
page accordingly: https://github.com/wikilinks/neleval/wiki/Convenience

**Comment by jnothman** [comment]
As per latest NIST discussions, it seems we should make this optional in the script... More fun.

**Comment by jnothman** [comment]
Okay. In the launcher scripts I've made providing excluded spans optional by having any additional arguments beyond the basic ones be passed to prepare-tac. This may be a bit user-unfriendly (command-line arg parsing is now less strict), but seems a decent mid-way solution.

**Comment by jnothman** [comment]
This also no longer invalidates former command-line usage of the `run_tac*` scripts, so I'm happier to merge it ASAP.

**Comment by jnothman** [comment]
To avoid putting this same feature in the `run_tac*_filtered` scripts, those now only take a single arg, the output dir of a whole evaluation.

**Comment by jnothman** [comment]
Ready to merge.

**Pull request merged**
